Implement Python slicing support for QByteArray
PySide2 for Python 3 didn't support get item by slice, e.g.
```
>>> from PySide2.QtCore import QByteArray
>>> ba = QByteArray('1234567890')
>>> ba[2:4]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sequence index must be integer, not 'slice'
```
This is because get item by slice is supported by mp_subscript.
But current PySide2 doesn't implemented it. So I added __mgetitem__ in
QByteArray. And we also need to keep __getitem__ to support iterate over
QByteArray.
Also removed the __getslice__ from QByteArray.

Task-number: PYSIDE-567
Change-Id: I01f79cc2ab8700da92155cfad96be2e98bb8b331
Reviewed-by: Alexandru Croitor <alexandru.croitor@qt.io>